#!/bin/bash

#test -e ../../../planck && $( cd ../../../planck && script/clean )

lein clean
rm -rf compiler
rm -rf resources
rm -rf aot-cache

git update-index --no-assume-unchanged ../../CSContext/bundle.c
git checkout -- ../../CSContext/bundle.c
